const CHANGE_ROUTE = 'CHANGE_ROUTE';
const UPDATE_TIMESTAMP = 'UPDATE_TIMESTAMP';

const GET_USER_DEFAULT = 'GET_USER_DEFAULT';
const LOGIN = 'LOGIN';
const LOGOUT = 'LOGOUT';
const REGISTER = 'REGISTER';
const UPDATE_USER_INFO = 'UPDATE_USER_INFO';
const UPDATE_PWD = 'UPDATE_PWD';

const actionTypes =  {
    CHANGE_ROUTE,
    UPDATE_TIMESTAMP,

    GET_USER_DEFAULT,
    LOGIN,
    LOGOUT,
    REGISTER,
    UPDATE_USER_INFO,
    UPDATE_PWD,
};

export default actionTypes;